use bevy::prelude::*;
use serde::{Deserialize, Serialize};

/// What kind of moment this entry preserves. Used by the journal UI (Phase G)
/// to tag, filter, and style entries.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum JournalKind {
    /// First time you saw a creature, prop, or biome.
    Encounter,
    /// You napped here (Phase B).
    Sleep,
    /// You gathered here.
    Gather,
    /// You placed a building here.
    Build,
    /// You examined something with the cat's curiosity verb (Phase B).
    Examine,
    /// A pre-seeded note from the previous traveler (Phase F echoes).
    Echo,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct JournalEntry {
    pub id: u32,
    /// In-game day at the time of the entry (from `WorldTime`).
    pub day: u32,
    pub kind: JournalKind,
    /// Free-form prose body. Generated by the system that writes the entry.
    pub body: String,
    /// Optional location association (XZ grid cell) -- used by `WorldMemory`
    /// to surface "what happened here" in tooltips.
    pub cell: Option<IVec2>,
}

#[derive(Resource, Default, Debug)]
pub struct Journal {
    pub entries: Vec<JournalEntry>,
    pub next_id: u32,
}

impl Journal {
    /// Append an entry. Returns its id so the caller can link the entry from
    /// `CellMemory.notes`.
    pub fn add(
        &mut self,
        day: u32,
        kind: JournalKind,
        body: impl Into<String>,
        cell: Option<IVec2>,
    ) -> u32 {
        let id = self.next_id;
        self.next_id = self.next_id.wrapping_add(1);
        self.entries.push(JournalEntry {
            id,
            day,
            kind,
            body: body.into(),
            cell,
        });
        id
    }
}
